# Generated by Django 6.0.3 on 2026-03-22 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('public_parking', 'Public Parking')], max_length=20)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fee if applicable', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='UserUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_unit', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('authorized_user', 'Authorized User')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_users', to='budget.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Unit Relationship',
                'verbose_name_plural': 'User Unit Relationships',
                'db_table': 'user_units',
                'unique_together': {('user', 'unit', 'start_date')},
            },
        ),
    ]
