# Generated by Django 6.0.3 on 2026-03-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_receipt_expensedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_es', models.CharField(max_length=50, verbose_name='Nombre en espanol')),
                ('category_type', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'expense', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.category'),
        ),
    ]
