# Generated by Django 6.0.3 on 2026-03-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_category_alter_expensedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto')], default='expense', max_length=10),
        ),
    ]
