# Generated by Django 6.0.3 on 2026-03-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_add_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payer', models.CharField(max_length=200, verbose_name='Pagador')),
                ('description', models.TextField(blank=True)),
                ('modified_by_user', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'income', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='budget.category')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_data', to='budget.receipt')),
            ],
            options={
                'verbose_name': 'Income Data',
                'verbose_name_plural': 'Income Data',
                'db_table': 'income_data',
            },
        ),
    ]
