# Generated by Django 6.0.3 on 2026-03-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_add_income_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.category'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='counterparty',
            field=models.CharField(blank=True, help_text='Vendor for expenses, payer for income', max_length=200),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='modified_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
