# Generated by Django 6.0.3 on 2026-03-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_migrate_transaction_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomedata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incomedata',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='ExpenseData',
        ),
        migrations.DeleteModel(
            name='IncomeData',
        ),
    ]
