# Generated by Django 6.0.3 on 2026-03-26 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_delete_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'upload_timestamp'], name='receipts_status_bda324_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['uploaded_by', 'status'], name='receipts_uploade_5a90fa_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'receipt_type', 'date'], name='receipts_status_e2f2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'receipt_type', 'uploaded_by'], name='receipts_status_00bac9_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['category', 'status'], name='receipts_categor_dfab92_idx'),
        ),
    ]
