# Generated by Django 6.0.3 on 2026-03-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_spanish_choices_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('inquilino', 'Inquilino'), ('sin_vinculo', 'Sin Vínculo')], default='inquilino', max_length=20),
        ),
    ]
